### ISSUE TITLE
Distribución de Roles

### ISSUE THREAD

**Issue by YeimmiBuenaventura** [YeimmiBuenaventura/Agora#11]
Líder Técnico: Alejandro Sotelo,
SCRUM Master: Yeimmi Buenaventura,
Lider Back-end: Stiven Saavedra,
Lider Front-end: Robinson Bernal,
Product Owner: Kevin Arias,
Team Developers: Valentina Idrogo.

**Comment by JymmyMurillo** [comment]
Quien es Product Owner?
