### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by YeimmiBuenaventura** [YeimmiBuenaventura/Agora#12]
Usuario: Valentina - Robinson;
Superadmin: Alejandro - Kevin;
Formador: ;

**Comment by Robin98123** [comment]
se hace vista Administración Bootcamps movil 
se hace vista  Administración Bootcamps movil  
se hace vista Workbook desktop
se hace vista Workbook movil
se hace vista Dashboard estudiante desktop
se hace vista Dashboard estudiante movil
se hace vista Dashboard proyectos desktop
se hace vista Dashboard estudiante proyectos movil

**Comment by Robin98123** [comment]
Día 07 de Febreo del 2023
se hacen vistas negativas de: 

vista Workbook desktop Desktop
vista Workbook desktop movil
vista Workbook desktop tablet

vista Dashboard estudiante desktop
vista Dashboard estudiante tablet
vista Dashboard estudiante movil

vista Dashboard proyectos desktop
vista Dashboard proyectos tablet
vista Dashboard proyectos movil

**Comment by Robin98123** [comment]
Día 08 de Febreo del 2023
se hacen vistas de:

vista Material de apoyo destopk | Recursos
vista Material de apoyo tablet | Recursos
vista Material de apoyo movil | Recursos

vista Material de apoyo destopk | clases grabadas 
vista Material de apoyo tablet | clases grabadas 
vista Material de apoyo movil | clases grabadas 

Vista Anuncios desktop | vista sin contenido
vista Anuncios tablet | vista sin contenido
vista Anuncios movil | vista sin contenido

vista Anuncios desktop 
vista Anuncios tablet
vista Anuncios movil

vista Perfil estudiantes desktop
vista Perfil estudiantes tablet
Perfil estudiantes movil

vistas negativas de: 

vista Material de apoyo destopk | Recursos
vista Material de apoyo tablet | Recursos
vista Material de apoyo movil | Recursos

vista Material de apoyo destopk | clases grabadas 
vista Material de apoyo tablet | clases grabadas 
vista Material de apoyo movil | clases grabadas 

Vista Anuncios desktop | vista sin contenido
vista Anuncios tablet | vista sin contenido
vista Anuncios movil | vista sin contenido

vista Anuncios desktop 
vista Anuncios tablet
vista Anuncios movil

vista Perfil estudiantes desktop
vista Perfil estudiantes tablet
Perfil estudiantes movilvista Material de apoyo destopk | Recursos
vista Material de apoyo tablet | Recursos
vista Material de apoyo movil | Recursos

vista Material de apoyo destopk | clases grabadas 
vista Material de apoyo tablet | clases grabadas 
vista Material de apoyo movil | clases grabadas 

Vista Anuncios desktop | vista sin contenido
vista Anuncios tablet | vista sin contenido
vista Anuncios movil | vista sin contenido

vista Anuncios desktop 
vista Anuncios tablet
vista Anuncios movil

vista Perfil estudiantes desktop
vista Perfil estudiantes tablet
Perfil estudiantes movil
